groups:
  projects:
    - project-abc
  datacenter:
    - dc-1
  environments:
    - dev
    - test

hosts:
  node1.project-abc.dc-1.dev.com:
    vars:
      var1: 123
      var2: 456
    groups:
      - project-abc
      - dc-1
      - dev
      
  node2.project-abc.dc-1.dev.com:
    vars:
      var1: 123
      var2: 456
    groups:
      - project-abc
      - dc-1
      - dev